version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.19
    volumes:
      - ./nginx/conf.d/develop.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./.env
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
      - "443:443"
    restart: "unless-stopped"

